# A basic one hidden layer neural network

In [101]:
import numpy as np

In [102]:
#declare 2 arrays x = input and y = output array
x = np.array([[0,1,0],[1,1,1],[1,0,0],[0,1,0]])
y = np.array([[0,1,1,0]])
l0 = x
print l0

[[0 1 0]
 [1 1 1]
 [1 0 0]
 [0 1 0]]


In [103]:
y = y.T
#.T transposes the y array
print y

[[0]
 [1]
 [1]
 [0]]


In [104]:
# sigmoid function
def sigmoid(x, deriv = True):
    if deriv == False:
        return 1/(1+np.exp(-x))
    else:
        return x*(1-x)

In [105]:
# generate a random seed
np.random.seed(1)

In [106]:
#synapse matrix is a matrix of weights multiplied to input matrix to get the required output
synapse = 2*np.random.rand(3,1) - 1
#taking the size of synapse matrix as 3x1 and its mean as 1
print synapse

# #normalising the synapse matrix
# synapse = sigmoid(synapse,False)
# print synapse

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [107]:
#iterating this several times to achieve the optimal output
for iter in xrange(1000):
    #multiplying the synapse with input layer to obtain hidden layer
    hiddenLayer = sigmoid(np.dot(l0,synapse),False)
    error = y - hiddenLayer
    
    #multiplying with derivative of input to see the magnitude of error
    delta = error*sigmoid(hiddenLayer,True)
    
    #multiplying with input so that input with 0 as value does not modify the delta dunction
    
    #adding the error to the synapse
    synapse += np.dot(l0.T,delta)

In [108]:
print hiddenLayer
#which should be close to y

[[ 0.02301114]
 [ 0.97737555]
 [ 0.99183289]
 [ 0.02301114]]


In [109]:
print error

[[-0.02301114]
 [ 0.02262445]
 [ 0.00816711]
 [-0.02301114]]


# Making a 3 layer neural network

In [110]:
#the new synapses will be used to generate 2 hidden layers
synapse0 = 2*np.random.rand(3,4) - 1
synapse1 = 2*np.random.rand(4,1) - 1

In [111]:
for iter in xrange(1000):
    layer0 = x
    layer1 = sigmoid(np.dot(layer0,synapse0),False)
    layer2 = sigmoid(np.dot(layer1,synapse1),False)
    
    #determining the error in layer2 and output
    error2 = y - layer2
    delta2 = error2*sigmoid(layer2,True)
    
    #determining the error in layer1
    error1 = np.dot(delta2,synapse1.T)
    delta1 = error1*sigmoid(layer1,True)
    
    synapse1 += np.dot(layer1.T,delta2)
    synapse0 += np.dot(layer0.T,delta1)

In [112]:
print layer2
#which should be close to y

[[ 0.0148819 ]
 [ 0.98386844]
 [ 0.98203443]
 [ 0.0148819 ]]


In [113]:
print error2

[[-0.0148819 ]
 [ 0.01613156]
 [ 0.01796557]
 [-0.0148819 ]]


# Making a neural network using Gradient Descent

In [114]:
# declare an array of alphas which determine the slope
alphas = [0.001,0.01,0.1,1,10,100]

In [128]:
#we have the same synapses, layers and errors.
synapse0 = 2*np.random.rand(3,4) - 1
synapse1 = 2*np.random.rand(4,1) - 1
#Only the alpha is multiplied with the sigmoid function to determine optimal rate of change

for a in alphas:
    print "\nError for alpha ="+ str(a)
    for iter in xrange(1000):
        layer1 = sigmoid(np.dot(layer0,synapse0),False)
        layer2 = sigmoid(np.dot(layer1,synapse1),False)

        error2 = layer2 - y
        delta2 = error2*sigmoid(layer2,True)
        
        error1 = np.dot(delta2,synapse1.T)
        delta1 = error1*sigmoid(layer1,True)
        
        synapse1 -= a*(np.dot(layer1.T,delta2))
        synapse0 -= a*(np.dot(layer0.T,delta1))
        
        if(iter%1000==0):
            print error2


Error for alpha =0.001
[[ 0.636947 ]
 [-0.3470557]
 [-0.3562663]
 [ 0.636947 ]]

Error for alpha =0.01
[[ 0.61147871]
 [-0.36854674]
 [-0.36952116]
 [ 0.61147871]]

Error for alpha =0.1
[[ 0.47226899]
 [-0.43188096]
 [-0.36089188]
 [ 0.47226899]]

Error for alpha =1
[[ 0.06875182]
 [-0.07828284]
 [-0.03862511]
 [ 0.06875182]]

Error for alpha =10
[[ 0.01488122]
 [-0.01701801]
 [-0.00858642]
 [ 0.01488122]]

Error for alpha =100
[[ 0.00415866]
 [-0.00479315]
 [-0.00256693]
 [ 0.00415866]]
