# A basic one hidden layer neural network

In [1]:
import numpy as np

In [32]:
#declare 2 arrays x = input and y = output array
x = np.array([[0,1,0],[1,1,1],[1,0,0],[0,1,0]])
y = np.array([[0,1,1,0]])
l0 = x
print l0

[[0 1 0]
 [1 1 1]
 [1 0 0]
 [0 1 0]]


In [33]:
y = y.T
#.T transposes the y array
print y

[[0]
 [1]
 [1]
 [0]]


In [34]:
# sigmoid function
def sigmoid(x, deriv = True):
    if deriv == False:
        return 1/(1+np.exp(-x))
    else:
        return x*(1-x)

In [35]:
# generate a random seed
np.random.seed(1)

In [46]:
#synapse matrix is a matrix of weights multiplied to input matrix to get the required output
synapse = 2*np.random.rand(3,1) - 1
#taking the size of synapse matrix as 3x1 and its mean as 1
print synapse

# #normalising the synapse matrix
# synapse = sigmoid(synapse,False)
# print synapse

[[-0.39533485]
 [-0.70648822]
 [-0.81532281]]


In [56]:
#iterating this several times to achieve the optimal output
for iter in xrange(1000):
    #multiplying the synapse with input layer to obtain hidden layer
    hiddenLayer = sigmoid(np.dot(l0,synapse),False)
    error = y - hiddenLayer
    
    #multiplying with derivative of input to see the magnitude of error
    delta = error*sigmoid(hiddenLayer,True)
    
    #multiplying with input so that input with 0 as value does not modify the delta dunction
    
    #adding the error to the synapse
    synapse += np.dot(l0.T,delta)

In [57]:
print hiddenLayer
#which should be close to y

[[ 0.01590968]
 [ 0.98439577]
 [ 0.99393605]
 [ 0.01590968]]


In [58]:
print error

[[-0.01590968]
 [ 0.01560423]
 [ 0.00606395]
 [-0.01590968]]


# Making a 3 layer neural network

In [59]:
#the new synapses will be used to generate 2 hidden layers
synapse0 = 2*np.random.rand(3,4) - 1
synapse1 = 2*np.random.rand(4,1) - 1

In [65]:
for iter in xrange(1000):
    layer0 = x
    layer1 = sigmoid(np.dot(layer0,synapse0),False)
    layer2 = sigmoid(np.dot(layer1,synapse1),False)
    
    #determining the error in layer2 and output
    error2 = y - layer2
    delta2 = error2*sigmoid(layer2,True)
    
    #determining the error in layer1
    error1 = np.dot(delta2,synapse1.T)
    delta1 = error1*sigmoid(layer1,True)
    
    synapse1 += np.dot(layer1.T,delta2)
    synapse0 += np.dot(layer0.T,delta1)

In [66]:
print layer2
#which should be close to y

[[ 0.01658672]
 [ 0.98101385]
 [ 0.98448505]
 [ 0.01658672]]


In [67]:
print error2

[[-0.01658672]
 [ 0.01898615]
 [ 0.01551495]
 [-0.01658672]]


# Making a neural network using Gradient Descent

In [ ]:
# declare an array of alphas which determine the slope